NOT = ['!', '$not']
IN = ['$in']
NIN = ['$nin']
AND = ['&&', '$and']
OR = ['||', '$or']
NOR = ['!||', '$nor']
EQ = ['=', '$eq']
LT = ['<', '$lt']
GT = ['>', '$gt']
LTE = ['<=', '$lte']
GTE = ['>=', '$gte']
NEQ = ['!=', '$neq']
LIKE = ['%%', '$re']
EXISTS = ['$ex']
TYPE = ['$t']
MOD = ['%', '$mod']
SIZE = ['$len']
